// ============================================================
// PDF Generator - Creates real PDF files in-browser
// ============================================================
import jsPDF from 'jspdf';
import type { CAPParameter, ContextSelection } from '@/types';

interface PDFData {
  companyName: string;
  capTitle: string;
  generatedDate: string;
  status: string;
  executiveSummary: string;
  contextSelections: ContextSelection[];
  materialityTable: CAPParameter[];
  roleResponseSummary: { role: string; count: number; avgScore: number }[];
  dimensionScores: { dimension: string; avgScore: number; weight: number; materiality: string }[];
  recommendations: string[];
  submissionCount: number;
}

export function generatePDF(data: PDFData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const addPage = () => {
    doc.addPage();
    y = margin;
  };

  const checkPageBreak = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      addPage();
    }
  };

  // ---- Cover Page ----
  doc.setFillColor(37, 99, 235); // primary blue
  doc.rect(0, 0, pageWidth, 120, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text('NexStep HR', margin, 30);

  doc.setFontSize(28);
  doc.text(data.capTitle, margin, 60, { maxWidth: contentWidth });

  doc.setFontSize(14);
  doc.text(data.companyName, margin, 80);

  doc.setFontSize(10);
  doc.text(`Generated: ${data.generatedDate}`, margin, 95);
  doc.text(`Status: ${data.status}`, margin, 105);

  doc.setTextColor(0, 0, 0);
  y = 140;

  doc.setFontSize(11);
  doc.text('CONFIDENTIAL', margin, y);
  y += 10;
  doc.setFontSize(9);
  doc.text('This report is generated by NexStep HR Contextual Assessment Platform.', margin, y);
  doc.text('The analysis is based on context-driven materiality and weighted responses.', margin, y + 5);

  // ---- Executive Summary ----
  addPage();
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', margin, y);
  y += 12;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const summaryLines = doc.splitTextToSize(data.executiveSummary, contentWidth);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 5 + 10;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total Submissions: ${data.submissionCount}`, margin, y);
  y += 15;

  // ---- Context Selections ----
  checkPageBreak(60);
  doc.setFontSize(18);
  doc.text('Context Selections', margin, y);
  y += 12;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  data.contextSelections.forEach(sel => {
    checkPageBreak(8);
    doc.setFont('helvetica', 'bold');
    doc.text(`${sel.categoryNameSnapshot}:`, margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(sel.valueLabelSnapshot, margin + 60, y);
    y += 7;
  });
  y += 10;

  // ---- Materiality Table ----
  checkPageBreak(80);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Materiality Analysis', margin, y);
  y += 12;

  // Table header
  doc.setFillColor(240, 240, 240);
  doc.rect(margin, y - 4, contentWidth, 8, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Dimension', margin + 2, y);
  doc.text('Weight %', margin + 80, y);
  doc.text('Materiality', margin + 120, y);
  y += 8;

  doc.setFont('helvetica', 'normal');
  data.materialityTable.forEach(param => {
    checkPageBreak(8);
    doc.text(param.label, margin + 2, y);
    doc.text(`${param.weightPct}%`, margin + 80, y);

    // Color coded materiality
    if (param.materialityLevel === 'High') doc.setTextColor(220, 38, 38);
    else if (param.materialityLevel === 'Medium') doc.setTextColor(217, 119, 6);
    else doc.setTextColor(22, 163, 74);
    doc.text(param.materialityLevel, margin + 120, y);
    doc.setTextColor(0, 0, 0);

    // Weight bar
    const barWidth = (param.weightPct / 25) * 40;
    doc.setFillColor(37, 99, 235);
    doc.rect(margin + 145, y - 3, barWidth, 4, 'F');

    y += 7;
  });
  y += 10;

  // ---- Dimension Scores ----
  addPage();
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Dimension Scores', margin, y);
  y += 12;

  doc.setFontSize(9);
  data.dimensionScores.forEach(dim => {
    checkPageBreak(12);
    doc.setFont('helvetica', 'bold');
    doc.text(dim.dimension, margin + 2, y);
    doc.setFont('helvetica', 'normal');
    doc.text(`Score: ${dim.avgScore}/100`, margin + 80, y);
    doc.text(`Weight: ${dim.weight}%`, margin + 125, y);

    // Score bar
    const barWidth = (dim.avgScore / 100) * 50;
    doc.setFillColor(37, 99, 235);
    doc.rect(margin + 2, y + 2, barWidth, 3, 'F');
    doc.setDrawColor(200, 200, 200);
    doc.rect(margin + 2, y + 2, 50, 3);

    y += 12;
  });
  y += 10;

  // ---- Role Response Summary ----
  checkPageBreak(60);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Role Response Summary', margin, y);
  y += 12;

  doc.setFillColor(240, 240, 240);
  doc.rect(margin, y - 4, contentWidth, 8, 'F');
  doc.setFontSize(9);
  doc.text('Role', margin + 2, y);
  doc.text('Responses', margin + 80, y);
  doc.text('Avg Score', margin + 120, y);
  y += 8;

  doc.setFont('helvetica', 'normal');
  data.roleResponseSummary.forEach(role => {
    checkPageBreak(8);
    doc.text(role.role, margin + 2, y);
    doc.text(String(role.count), margin + 80, y);
    doc.text(`${role.avgScore}/100`, margin + 120, y);
    y += 7;
  });
  y += 10;

  // ---- Recommendations ----
  checkPageBreak(40);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Recommendations', margin, y);
  y += 12;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  data.recommendations.forEach((rec, i) => {
    checkPageBreak(20);
    const lines = doc.splitTextToSize(`${i + 1}. ${rec}`, contentWidth - 5);
    doc.text(lines, margin + 2, y);
    y += lines.length * 5 + 5;
  });

  // ---- Appendix ----
  addPage();
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Appendix', margin, y);
  y += 12;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Scoring Methodology:', margin, y);
  y += 6;
  doc.text('- Likert scale responses (1-5) are converted to dimension scores (0-100)', margin + 5, y);
  y += 5;
  doc.text('- Dimension scores are weighted by context-based materiality percentages', margin + 5, y);
  y += 5;
  doc.text('- Materiality levels: High (>=14%), Medium (9-13.99%), Low (<9%)', margin + 5, y);
  y += 5;
  doc.text('- Recommendations are generated based on materiality-score gap analysis', margin + 5, y);
  y += 15;

  doc.text('Generated by NexStep HR Contextual Assessment Platform', margin, y);
  y += 5;
  doc.text(`Report Date: ${data.generatedDate}`, margin, y);

  // Save
  doc.save(`${data.capTitle.replace(/[^a-zA-Z0-9]/g, '_')}_Report.pdf`);
}
