import { useState } from 'react';
import {
  HelpCircle,
  ChevronDown,
  ChevronUp,
  Send,
  MessageCircle,
} from 'lucide-react';
import { PageHeader } from '@/components/shared/page-header';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';

interface FAQItem {
  question: string;
  answer: string;
}

const FAQ_ITEMS: FAQItem[] = [
  {
    question: 'What is a CAP and how does it work?',
    answer:
      'A CAP (Comprehensive Assessment Plan) is a structured evaluation process. Companies create a CAP, select context parameters, generate weighted outputs, invite responders to complete surveys, and then generate analytical reports based on the collected data. As a consultant, you can view all CAPs for your assigned companies.',
  },
  {
    question: 'How do I view CAPs across my assigned companies?',
    answer:
      'Navigate to the "CAPs" section in the sidebar. This shows all CAPs across your assigned companies in a single searchable table. You can filter by title, company name, or status. Click on any CAP to view its detailed read-only information including context selections, outputs, and submission counts.',
  },
  {
    question: 'Can I edit company data or CAP configurations?',
    answer:
      'As a consultant, you have read-only access to company data and CAP configurations. You can view all information including context selections, outputs, submissions, and reports, but you cannot modify any data. If changes are needed, please contact the company sponsor or your Super Admin.',
  },
  {
    question: 'How are reports generated and who can access them?',
    answer:
      'Reports are generated by the company sponsor or Sub Admin once a CAP has reached its minimum submission threshold. As a consultant, you can view generated reports through the Reports section. Reports come in two access levels: Basic (free) and Advanced (requires payment or bypass code).',
  },
  {
    question: 'What do the materiality levels (High, Medium, Low) mean?',
    answer:
      'Materiality levels indicate the relative importance of each assessment parameter. High materiality parameters have the greatest weight in the overall assessment and should receive the most attention in recommendations. These levels are determined by platform-wide thresholds set by the Super Admin and the specific context selections made for each CAP.',
  },
  {
    question: 'How do I get assigned to new companies?',
    answer:
      'Company assignments are managed by your Super Admin. Contact them to request access to additional companies. Once assigned, the new company and its CAPs will automatically appear in your dashboard and sidebar navigation.',
  },
];

export default function ConsultantHelp() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);
  const [contactName, setContactName] = useState('');
  const [contactEmail, setContactEmail] = useState('');
  const [contactMessage, setContactMessage] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const handleSubmitContact = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!contactName.trim() || !contactEmail.trim() || !contactMessage.trim()) {
      toast.error('Please fill in all fields.');
      return;
    }
    setSubmitting(true);
    // Mock submit
    await new Promise((resolve) => setTimeout(resolve, 1000));
    setSubmitting(false);
    toast.success(
      'Support request submitted. We will get back to you within 24 hours.'
    );
    setContactName('');
    setContactEmail('');
    setContactMessage('');
  };

  return (
    <div className="p-6 space-y-6">
      <PageHeader
        title="Help Center"
        subtitle="Frequently asked questions and support contact"
        breadcrumbs={[
          { label: 'Consultant', href: '/consultant' },
          { label: 'Help' },
        ]}
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* FAQ Section */}
        <div className="lg:col-span-2">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg flex items-center gap-2">
                <HelpCircle className="h-5 w-5 text-muted-foreground" />
                Frequently Asked Questions
              </CardTitle>
              <CardDescription>
                Click on a question to expand its answer.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-2">
              {FAQ_ITEMS.map((item, index) => (
                <div
                  key={index}
                  className="border rounded-lg overflow-hidden"
                >
                  <button
                    onClick={() => toggleFAQ(index)}
                    className="w-full flex items-center justify-between p-4 text-left hover:bg-muted/50 transition-colors"
                  >
                    <span className="text-sm font-medium pr-4">
                      {item.question}
                    </span>
                    {openIndex === index ? (
                      <ChevronUp className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                    ) : (
                      <ChevronDown className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                    )}
                  </button>
                  {openIndex === index && (
                    <div className="px-4 pb-4">
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        {item.answer}
                      </p>
                    </div>
                  )}
                </div>
              ))}
            </CardContent>
          </Card>
        </div>

        {/* Contact Support Form */}
        <div>
          <Card>
            <CardHeader>
              <CardTitle className="text-lg flex items-center gap-2">
                <MessageCircle className="h-5 w-5 text-muted-foreground" />
                Contact Support
              </CardTitle>
              <CardDescription>
                Need further help? Send us a message and we will respond within
                24 hours.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleSubmitContact} className="space-y-4">
                <div className="space-y-2">
                  <label className="text-sm font-medium">Your Name</label>
                  <Input
                    value={contactName}
                    onChange={(e) => setContactName(e.target.value)}
                    placeholder="Enter your name"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Email Address</label>
                  <Input
                    type="email"
                    value={contactEmail}
                    onChange={(e) => setContactEmail(e.target.value)}
                    placeholder="your@email.com"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Message</label>
                  <Textarea
                    value={contactMessage}
                    onChange={(e) => setContactMessage(e.target.value)}
                    placeholder="Describe your issue or question..."
                    rows={5}
                  />
                </div>
                <Button
                  type="submit"
                  className="w-full"
                  disabled={submitting}
                >
                  <Send className="h-4 w-4 mr-2" />
                  {submitting ? 'Sending...' : 'Send Message'}
                </Button>
              </form>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
